In [1]:
import torch
import torch.nn as nn
import numpy
torch.cuda.is_available()

False

In [7]:
a=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a=[0]*2
a

[0, 0]

In [15]:
m=nn.Softmax()
a = torch.randn(1,4)
print(a)
b = m(a)
print(b)
print(b[0][0])

tensor([[-0.8685, -0.5980,  0.8497,  0.2123]])
tensor([[0.0923, 0.1210, 0.5146, 0.2721]])
tensor(0.0923)


/home/qning2/Software/anaconda2/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  after removing the cwd from sys.path.


In [4]:
a=[]
a.append([1,2])
a.append([3,4])
print(a)

[[1, 2], [3, 4]]


In [5]:
torch.tensor(a)

tensor([[1, 2],
        [3, 4]])

In [12]:
a=torch.Tensor([0.5,0.3]).view(1,-1)
print(a)
torch.LongTensor([int(t/0.1) for t in a[0]])

tensor([[0.5000, 0.3000]])


tensor([5, 3])

In [37]:
x = numpy.zeros((3,2),dtype=int)
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [3]:
torch.rand(2,3,4)

tensor([[[0.9521, 0.9967, 0.1607, 0.7907],
         [0.8456, 0.3824, 0.7912, 0.0382],
         [0.3102, 0.7325, 0.0940, 0.1879]],

        [[0.4267, 0.2511, 0.1825, 0.4770],
         [0.9533, 0.4725, 0.2731, 0.2238],
         [0.1107, 0.0978, 0.0631, 0.4459]]])

In [27]:
x=torch.empty(5,3)
x

tensor([[-9549829231815554381622804480.0000,                             0.0000,
         -9549829231815554381622804480.0000],
        [                            0.0000,                             0.0000,
                                     0.0000],
        [                            0.0000,                             0.0000,
         -9516664052006360863287017472.0000],
        [                            0.0000,                             0.0000,
                                     0.0000],
        [                            0.0000,                             0.0000,
                                     0.0000]])

In [14]:
y=torch.rand(5,1,3,dtype=torch.float)
y

tensor([[[0.9740, 0.9405, 0.0255]],

        [[0.4610, 0.0346, 0.5077]],

        [[0.8653, 0.0566, 0.2366]],

        [[0.0165, 0.3161, 0.1636]],

        [[0.2814, 0.4114, 0.6831]]])

In [24]:
y[-1][:][:]

tensor([[0.2814, 0.4114, 0.6831]])

In [6]:
y

tensor([[0.3026, 0.8112, 0.6256],
        [0.3669, 0.7200, 0.9576],
        [0.3551, 0.6668, 0.3571],
        [0.2323, 0.5797, 0.0392],
        [0.9755, 0.6141, 0.6064]])

In [4]:
z=torch.zeros(5,3,dtype=torch.int)
z

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [13]:
w=torch.tensor([1.1,2.2])
w

torch.Size([2])

In [28]:
w = torch.full([2,3],100)

tensor([[100., 100., 100.],
        [100., 100., 100.]])

In [6]:
a=x.new_ones(2,4)
print(a)
print(a.size())

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([2, 4])


In [7]:
result = torch.empty(5,3)
# result = x+y
torch.add(x,y,out=result)
print(result[:,1])
print(result)

tensor([2.6021e-01,        nan, 1.5564e+28, 1.3788e-01, 3.0313e+32])
tensor([[6.1829e+18, 2.6021e-01, 6.1829e+18],
        [3.8148e-01,        nan, 2.0543e-01],
        [7.6194e+31, 1.5564e+28, 1.8484e+31],
        [1.8370e+25, 1.3788e-01, 2.7517e+12],
        [7.5338e+28, 3.0313e+32, 6.3828e+28]])


In [8]:
y.add_(x)
y

tensor([[6.1829e+18, 2.6021e-01, 6.1829e+18],
        [3.8148e-01,        nan, 2.0543e-01],
        [7.6194e+31, 1.5564e+28, 1.8484e+31],
        [1.8370e+25, 1.3788e-01, 2.7517e+12],
        [7.5338e+28, 3.0313e+32, 6.3828e+28]])

In [9]:
print(y)
print(y.view(-1,5))

tensor([[6.1829e+18, 2.6021e-01, 6.1829e+18],
        [3.8148e-01,        nan, 2.0543e-01],
        [7.6194e+31, 1.5564e+28, 1.8484e+31],
        [1.8370e+25, 1.3788e-01, 2.7517e+12],
        [7.5338e+28, 3.0313e+32, 6.3828e+28]])
tensor([[6.1829e+18, 2.6021e-01, 6.1829e+18, 3.8148e-01,        nan],
        [2.0543e-01, 7.6194e+31, 1.5564e+28, 1.8484e+31, 1.8370e+25],
        [1.3788e-01, 2.7517e+12, 7.5338e+28, 3.0313e+32, 6.3828e+28]])


In [45]:
b=a.numpy()
print(a)
print(b)
a.add(1)
print(a)
print(b)
a.add_(1)
print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int16)
[[1 1 1 1]
 [1 1 1 1]]
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int16)
[[1 1 1 1]
 [1 1 1 1]]
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]], dtype=torch.int16)
[[2 2 2 2]
 [2 2 2 2]]


In [47]:
device=torch.device("cuda")
device

device(type='cuda')

In [6]:
a=',test, kojo     233   fsd\t4'
print(a.split(','))
# print(a.split()[0][:-3])

['', 'test', ' kojo     233   fsd\t4']
